import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'bn' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  getCategoryTranslation: (category: string) => string;
  getUnionTranslation: (union: string) => string;
  getDistrictTranslation: (district: string) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'bn';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  // Simple translation helper
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const getCategoryTranslation = (category: string): string => {
    const categoryMap: { [key: string]: string } = {
      'সমগ্র বরগুনা': 'category.all_barguna',
      'বরগুনা সদর': 'category.barguna_sadar',
      'আমতলী': 'category.amtali',
      'পাথরঘাটা': 'category.patharghata',
      'বেতাগী': 'category.betagi',
      'বামনা': 'category.bamna',
      'তালতলী': 'category.taltali',
      'সারাদেশ': 'category.saradesh',
      'বিশ্ব': 'category.bishwo'
    };

    const key = categoryMap[category];
    return key ? t(key) : category;
  };

  const getUnionTranslation = (union: string): string => {
    const unionMap: { [key: string]: string } = {
      'বদরখালী': 'union.badarkhali',
      'গৌরীচন্না': 'union.gourichanna',
      'ফুলঝুড়ি': 'union.fuljhuri',
      'কেওড়াবুনিয়া': 'union.keorabunia',
      'আয়লাপাতাকাটা': 'union.aylapatakata',
      'বুড়িরচর': 'union.burirchar',
      'ঢলুয়া': 'union.dholua',
      'বরগুনা সদর': 'union.barguna_sadar',
      'এম বালিয়াতলী': 'union.m_baliatali',
      'নলটোনা': 'union.naltona',
      'গুলিসাখালী': 'union.gulisakhali',
      'কুকুয়া': 'union.kukua',
      'আঠারগাছিয়া': 'union.athargachia',
      'হলদিয়া': 'union.haldiya',
      'চাওড়া': 'union.chaora',
      'আমতলী সদর': 'union.amtali_sadar',
      'আড়পাঙ্গাশিয়া': 'union.arpangashia',
      'পঁচাকোড়ালিয়া': 'union.panchakoralia',
      'ছোটবগী': 'union.chotobogi',
      'কড়ইবাড়ীয়া': 'union.koraibaria',
      'শারিকখালী': 'union.sharikkhali',
      'বড়বগী সদর': 'union.borobogi_sadar',
      'নিশানবাড়ীয়া': 'union.nishanbaria',
      'সোনাকাটা': 'union.sonakata',
      'বিবিচিনি': 'union.bibichini',
      'বেতাগী সদর': 'union.betagi_sadar',
      'হোসনাবাদ': 'union.hosnabad',
      'মোকামিয়া': 'union.mokamia',
      'বুড়ামজুমদার': 'union.buramajumdar',
      'কাজিরাবাদ': 'union.kajirabad',
      'সরিষামুড়ি': 'union.sorishamuri',
      'বুকাবুনিয়া': 'union.bukabunia',
      'বামনা সদর': 'union.bamna_sadar',
      'রামনা': 'union.ramna',
      'ডৌয়াতলা': 'union.douatala',
      'রায়হানপুর ইউনিয়ন': 'union.raihanpur',
      'নাচনাপাড়া ইউনিয়ন': 'union.nachnapara',
      'চরদুয়ানী ইউনিয়ন': 'union.charduani',
      'পাথরঘাটা সদর ইউনিয়ন': 'union.patharghata_sadar',
      'কালমেঘা ইউনিয়ন': 'union.kalmegha',
      'কাকচিড়া ইউনিয়ন': 'union.kakchira',
      'কাঠালতলী ইউনিয়ন': 'union.kathaltali'
    };

    const key = unionMap[union];
    return key ? t(key) : union;
  };

  const getDistrictTranslation = (district: string): string => {
    const districtMap: { [key: string]: string } = {
      'বরগুনা': 'district.barguna',
      'আমতলী': 'district.amtali',
      'পাথরঘাটা': 'district.patharghata',
      'বেতাগী': 'district.betagi',
      'বামনা': 'district.bamna',
      'তালতলী': 'district.taltali'
    };

    const key = districtMap[district];
    return key ? t(key) : district;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getCategoryTranslation, getUnionTranslation, getDistrictTranslation }}>
      <div className={language === 'en' ? 'font-inter' : 'font-sans'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations: Record<Language, Record<string, string>> = {
  bn: {
    'nav.home': 'প্রচ্ছদ',
    'nav.more': 'আরও',
    'nav.search': 'খুঁজুন...',
    'nav.search_placeholder': 'সংবাদ খুঁজুন...',
    'nav.unions': 'এলাকা ভিত্তিক সংবাদ',
    'nav.download': 'ডাউনলোড (Windows)',
    'footer.about': 'আমাদের সম্পর্কে',
    'footer.privacy': 'গোপনীয়তা নীতি',
    'footer.terms': 'শর্তাবলী',
    'footer.contact': 'যোগাযোগ',
    'footer.editor': 'সম্পাদক ও প্রকাশক',
    'footer.upazila': 'উপজেলা সমূহ',
    'footer.description': 'বরগুনা জেলার সর্বশেষ সংবাদ, রাজনীতি, অর্থনীতি, বিনোদন, খেলাধুলা এবং লাইফস্টাইলের নির্ভরযোগ্য উৎস। সত্যের সন্ধানে আমরা সর্বদা অবিচল।',
    'about.title': 'আমাদের সম্পর্কে',
    'about.subtitle': 'দৈনিক বরগুনা: সত্যের সন্ধানে অবিরাম',
    'contact.title': 'যোগাযোগ',
    'contact.subtitle': 'আমাদের সাথে যোগাযোগ করুন',
    'privacy.title': 'গোপনীয়তা নীতি',
    'terms.title': 'শর্তাবলী',
    'editor.title': 'সম্পাদক ও প্রকাশক',
    'editor.contact_desc': 'দৈনিক বরগুনা-এর সম্পাদক ও প্রকাশক মোঃ জুনায়েদ আল হাসান-এর সাথে যোগাযোগ করতে নিচের মাধ্যমগুলো ব্যবহার করুন।',
    'nav.back': 'পিছনে যান',
    'notfound.title': '৪০৪ - পাতা পাওয়া যায়নি',
    'notfound.code': '৪০৪',
    'notfound.heading': 'দুঃখিত, এই পাতাটি খুঁজে পাওয়া যায়নি!',
    'notfound.desc': 'আপনি যে সংবাদ বা পাতাটি খুঁজছেন তা হয়তো মুছে ফেলা হয়েছে অথবা এর ঠিকানা পরিবর্তন করা হয়েছে। সঠিক ঠিকানাটি পুনরায় যাচাই করুন।',
    'notfound.home': 'প্রচ্ছদে ফিরে যান',
    'notfound.back': 'পূর্ববর্তী পাতায় যান',
    'category.all_barguna': 'সমগ্র বরগুনা',
    'category.barguna_sadar': 'বরগুনা সদর',
    'category.amtali': 'আমতলী',
    'category.patharghata': 'পাথরঘাটা',
    'category.betagi': 'বেতাগী',
    'category.bamna': 'বামনা',
    'category.taltali': 'তালতলী',
    'category.saradesh': 'সারাদেশ',
    'category.bishwo': 'বিশ্ব',
    'union.badarkhali': 'বদরখালী',
    'union.gourichanna': 'গৌরীচন্না',
    'union.fuljhuri': 'ফুলঝুড়ি',
    'union.keorabunia': 'কেওড়াবুনিয়া',
    'union.aylapatakata': 'আয়লাপাতাকাটা',
    'union.burirchar': 'বুড়িরচর',
    'union.dholua': 'ঢলুয়া',
    'union.barguna_sadar': 'বরগুনা সদর',
    'union.m_baliatali': 'এম বালিয়াতলী',
    'union.naltona': 'নলটোনা',
    'union.gulisakhali': 'গুলিসাখালী',
    'union.kukua': 'কুকুয়া',
    'union.athargachia': 'আঠারগাছিয়া',
    'union.haldiya': 'হলদিয়া',
    'union.chaora': 'চাওড়া',
    'union.amtali_sadar': 'আমতলী সদর',
    'union.arpangashia': 'আড়পাঙ্গাশিয়া',
    'union.panchakoralia': 'পঁচাকোড়ালিয়া',
    'union.chotobogi': 'ছোটবগী',
    'union.koraibaria': 'কড়ইবাড়ীয়া',
    'union.sharikkhali': 'শারিকখালী',
    'union.borobogi_sadar': 'বড়বগী সদর',
    'union.nishanbaria': 'নিশানবাড়ীয়া',
    'union.sonakata': 'সোনাকাটা',
    'union.bibichini': 'বিবিচিনি',
    'union.betagi_sadar': 'বেতাগী সদর',
    'union.hosnabad': 'হোসনাবাদ',
    'union.mokamia': 'মোকামিয়া',
    'union.buramajumdar': 'বুড়ামজুমদার',
    'union.kajirabad': 'কাজিরাবাদ',
    'union.sorishamuri': 'সরিষামুড়ি',
    'union.bukabunia': 'বুকাবুনিয়া',
    'union.bamna_sadar': 'বামনা সদর',
    'union.ramna': 'রামনা',
    'union.douatala': 'ডৌয়াতলা',
    'union.raihanpur': 'রায়হানপুর ইউনিয়ন',
    'union.nachnapara': 'নাচনাপাড়া ইউনিয়ন',
    'union.charduani': 'চরদুয়ানী ইউনিয়ন',
    'union.patharghata_sadar': 'পাথরঘাটা সদর ইউনিয়ন',
    'union.kalmegha': 'কালমেঘা ইউনিয়ন',
    'union.kakchira': 'কাকচিড়া ইউনিয়ন',
    'union.kathaltali': 'কাঠালতলী ইউনিয়ন',
    'district.barguna': 'বরগুনা',
    'district.amtali': 'আমতলী',
    'district.patharghata': 'পাথরঘাটা',
    'district.betagi': 'বেতাগী',
    'district.bamna': 'বামনা',
    'district.taltali': 'তালতলী',
    'site.title': 'দৈনিক বরগুনা',
    'news.latest_desc': 'বিষয়ক সর্বশেষ সংবাদ - দৈনিক বরগুনা',
    'news.headlines': 'শিরোনাম',
    'news.live_now': 'সরাসরি সম্প্রচার 🔴',
    'news.live_desc': 'জাতীয় সংসদের অধিবেশন সরাসরি সম্প্রচারিত হচ্ছে',
    'news.watch_live': 'সরাসরি দেখুন',
    'news.area': 'এলাকা',
    'news.all_areas': 'সব এলাকা',
    'news.attached_file': 'সংযুক্ত ফাইল',
    'news.file_attached_desc': 'এই সংবাদের সাথে একটি ফাইল সংযুক্ত আছে',
    'news.view_file': 'ফাইল দেখুন',
    'news.more_images': 'আরও ছবি',
    'news.topic': 'বিষয়',
    'news.related': 'সম্পর্কিত সংবাদ',
    'news.views': 'বার দেখা হয়েছে',
    'news.share': 'শেয়ার করুন',
    'news.search_results': 'অনুসন্ধান ফলাফল',
    'news.search_news': 'সংবাদ অনুসন্ধান',
    'news.filter': 'ফিল্টার',
    'news.all_categories': 'সব বিভাগ',
    'news.all_authors': 'সব লেখক',
    'news.start_date': 'শুরুর তারিখ',
    'news.end_date': 'শেষের তারিখ',
    'news.clear_filters': 'ফিল্টার মুছুন',
    'news.no_results': 'কোন ফলাফল পাওয়া যায়নি',
    'news.area_latest': 'এলাকার সর্বশেষ সংবাদ',
    'news.no_news_area': 'এই এলাকায় কোন সংবাদ নেই',
    'news.no_news_area_desc': '{union} এলাকায় বর্তমানে কোন সংবাদ পাওয়া যায়নি।',
    'news.search_union': 'ইউনিয়ন খুঁজুন...',
    'news.all_unions': 'সব ইউনিয়ন দেখুন',
    'news.no_union': 'কোন ইউনিয়ন পাওয়া যায়নি',
    'footer.editor_name': 'মোঃ জুনায়েদ আল হাসান',
    'footer.address': 'সদর রোড, বরগুনা - ৮৭০০, বাংলাদেশ',
    'footer.email': 'ইমেইল',
    'footer.copyright': '© {year} দৈনিক বরগুনা। সর্বস্বত্ব সংরক্ষিত।',
    'common.read_more': 'আরও পড়ুন',
    'common.show_less': 'কম দেখুন',
    'common.latest': 'সর্বশেষ সংবাদ',
    'common.popular': 'জনপ্রিয়',
    'common.share': 'শেয়ার করুন',
    'common.date_en': 'ইংরেজি তারিখ',
    'common.date_bn': 'বাংলা তারিখ',
    'common.date_hijri': 'হিজরি তারিখ',
    'ramadan.iftar': 'ইফতারের সময়',
    'ramadan.sehri': 'সেহরির সময়',
    'ramadan.sehri_end': 'সেহরির শেষ সময়',
    'ramadan.iftar_time': 'ইফতারের সময়',
    'ramadan.timer': 'রমজান টাইমার',
    'ramadan.enable_alert': 'অ্যালার্ট চালু করুন',
    'ramadan.stop_azan': 'আজান থামান',
    'news.district': 'জেলা',
    'news.area_news': 'এলাকার খবর',
    'news.published': 'প্রকাশিত',
    'news.file': 'সংযুক্ত ফাইল',
    'news.video': 'ভিডিও',
    'news.images': 'আরও ছবি',
    'news.no_news': 'কোন সংবাদ পাওয়া যায়নি',
    'news.no_news_category': 'এই বিভাগে কোনো সংবাদ পাওয়া যায়নি।',
    'news.count': 'টি সংবাদ',
    'search.results': 'অনুসন্ধানের ফলাফল',
    'search.no_results': 'দুঃখিত, আপনার অনুসন্ধানের সাথে মেলে এমন কিছু পাওয়া যায়নি।',
    'download.title': 'অ্যাপ ডাউনলোড',
    'download.desc': 'দৈনিক বরগুনা অ্যাপ ডাউনলোড করুন',
    'download.heading': 'দৈনিক বরগুনা অ্যাপ ডাউনলোড',
    'download.subheading': 'আমাদের অফিসিয়াল অ্যাপটি ডাউনলোড করুন এবং দ্রুততম সময়ে সব খবর আপনার হাতের মুঠোয় পান। নিচে অ্যাপটি ডাউনলোড করার নির্দেশাবলী দেওয়া হলো:',
    'download.instructions_title': 'ডাউনলোড ও ইনস্টল নির্দেশাবলী:',
    'download.step1': '<strong>প্রথমে এখনই ডাউনলোড করুন এ চাপ দিন:</strong> তারপর "Download anyway" তে চাপ দিয়ে অ্যাপটি ডাউনলোড করুন।',
    'download.step2': '<strong>INSTALL এ চাপ দিন:</strong> ডাউনলোড করা ফাইলটি ওপেন করে INSTALL বাটনে ক্লিক করুন।',
    'download.step3': '<strong>More Details এ চাপ দিন:</strong> যদি "Play Protect hasn\'t seen this app" মেসেজটি আসে, তবে "More details" অপশনে ক্লিক করুন।',
    'download.step4': '<strong>Install Without Scanning এ চাপ দিন:</strong> এরপর "Install without scanning" বাটনে ক্লিক করুন।',
    'download.step5': '<strong>নিরাপত্তা যাচাই:</strong> আপনার ফোনের Fingerprint বা Pin দিয়ে অনুমতি দিন, তারপর অ্যাপটি ইনস্টল সম্পন্ন করুন।',
    'download.button': 'এখনই ডাউনলোড করুন',
    'admin.add_new_news': 'নতুন সংবাদ যোগ করুন',
    'admin.title': 'শিরোনাম',
    'admin.title_placeholder': 'সংবাদের শিরোনাম লিখুন',
    'admin.short_description': 'সংক্ষিপ্ত বিবরণ',
    'admin.short_description_placeholder': 'সংবাদের সংক্ষিপ্ত বিবরণ লিখুন',
    'admin.main_news': 'মূল সংবাদ',
    'admin.main_news_placeholder': 'এখানে মূল সংবাদ লিখুন...',
    'admin.media': 'মিডিয়া',
    'admin.image_url': 'ছবির URL',
    'admin.additional_images': 'অতিরিক্ত ছবি',
    'admin.image_link_placeholder': 'ছবির লিংক (https://...)',
    'admin.image_caption_placeholder': 'ছবির ক্যাপশন (ঐচ্ছিক)',
    'admin.video_url': 'ভিডিও URL',
    'admin.video_url_placeholder': 'ইউটিউব বা অন্য ভিডিও লিংক',
    'admin.metadata': 'মেটাডেটা',
    'admin.file_link': 'ফাইল লিংক',
    'admin.file_link_placeholder': 'পিডিএফ বা অন্য ফাইলের লিংক',
    'admin.category': 'ক্যাটাগরি',
    'admin.district': 'জেলা',
    'admin.select_district': 'জেলা নির্বাচন করুন',
    'admin.union_area': 'ইউনিয়ন/এলাকা',
    'admin.search_union_placeholder': 'ইউনিয়ন খুঁজুন...',
    'admin.reporter': 'রিপোর্টার',
    'admin.keywords': 'কিওয়ার্ড (SEO)',
    'admin.keywords_placeholder': 'কমা দিয়ে আলাদা করুন (যেমন: বরগুনা, খবর, রাজনীতি)',
    'admin.mark_as_trending': 'ট্রেন্ডিং হিসেবে চিহ্নিত করুন',
    'admin.trending_description': 'এই সংবাদটি হোমপেজের ট্রেন্ডিং সেকশনে দেখাবে',
    'admin.preview': 'প্রিভিউ',
    'admin.ramadan_timer': 'রমজান টাইমার',
    'admin.sehri_time': 'সেহরির সময়',
    'admin.timer_alert_on': 'টাইমার অ্যালার্ট চালু আছে',
    'admin.dashboard': 'ড্যাশবোর্ড',
    'admin.confirm_delete': 'আপনি কি নিশ্চিত যে এই সংবাদটি মুছে ফেলতে চান?',
    'admin.delete_success': 'সংবাদটি সফলভাবে মুছে ফেলা হয়েছে।',
    'admin.delete_error': 'সংবাদ মুছতে সমস্যা হয়েছে।',
    'admin.confirm_title_delete': 'আপনি কি নিশ্চিত যে এই শিরোনামটি মুছে ফেলতে চান?',
    'admin.title_delete_success': 'শিরোনামটি মুছে ফেলা হয়েছে।',
    'admin.title_delete_error': 'শিরোনাম মুছতে সমস্যা হয়েছে।',
    'admin.confirm_ad_delete': 'আপনি কি নিশ্চিত যে এই বিজ্ঞাপনটি মুছে ফেলতে চান?',
    'admin.ad_delete_success': 'বিজ্ঞাপনটি মুছে ফেলা হয়েছে।',
    'admin.ad_delete_error': 'বিজ্ঞাপন মুছতে সমস্যা হয়েছে।',
    'admin.social_update_success': 'সোশ্যাল মিডিয়া লিংক সফলভাবে আপডেট করা হয়েছে।',
    'admin.social_update_error': 'লিংক আপডেট করতে সমস্যা হয়েছে।',
    'admin.ramadan_update_success': 'রমজানের সময়সূচী সফলভাবে আপডেট করা হয়েছে।',
    'admin.ramadan_update_error': 'সময়সূচী আপডেট করতে সমস্যা হয়েছে।',
    'admin.page_update_success': 'পেজ সেটিংস সফলভাবে আপডেট করা হয়েছে।',
    'admin.page_update_error': 'সেটিংস আপডেট করতে সমস্যা হয়েছে।',
    'admin.title_update_success': 'শিরোনাম আপডেট করা হয়েছে।',
    'admin.title_update_error': 'শিরোনাম আপডেট করতে সমস্যা হয়েছে।',
    'admin.ad_update_success': 'বিজ্ঞাপন আপডেট করা হয়েছে।',
    'admin.ad_update_error': 'বিজ্ঞাপন আপডেট করতে সমস্যা হয়েছে।',
    'admin.title_status_on': 'শিরোনাম চালু করা হয়েছে।',
    'admin.title_status_off': 'শিরোনাম বন্ধ করা হয়েছে।',
    'admin.ad_status_on': 'বিজ্ঞাপন চালু করা হয়েছে।',
    'admin.ad_status_off': 'বিজ্ঞাপন বন্ধ করা হয়েছে।',
    'admin.passcode_locked': '৩ বার ভুল পাসকোড! ১ মিনিট অপেক্ষা করুন।',
    'admin.passcode_wrong': 'ভুল পাসকোড! আর {attempts} বার চেষ্টা করতে পারবেন।',
    'admin.passcode_verify': 'পাসকোড যাচাই',
    'admin.enter_passcode': 'পাসকোড দিন',
    'admin.wait_seconds': 'অপেক্ষা করুন {seconds} সেকেন্ড',
    'admin.passcode': 'পাসকোড',
    'admin.verify': 'যাচাই করুন',
    'error.title': 'দুঃখিত, একটি সমস্যা হয়েছে',
    'error.message': 'অ্যাপ্লিকেশনটি লোড করতে সমস্যা হচ্ছে। অনুগ্রহ করে পেজটি রিফ্রেশ করুন অথবা কিছুক্ষণ পর আবার চেষ্টা করুন।',
    'error.refresh': 'পেজ রিফ্রেশ করুন',
    'admin.employee': 'কর্মচারী',
    'admin.firebase_not_connected': 'Firebase কানেক্ট করা নেই!',
    'admin.firebase_not_connected_desc': 'আপনার Vercel বা হোস্টিং এনভায়রনমেন্টে Firebase এর API Key গুলো সেট করা নেই। এর ফলে রিয়েল-টাইম ডেটাবেস কাজ করবে না। অনুগ্রহ করে Vercel Settings এ গিয়ে ',
    'admin.firebase_not_connected_desc2': ' ভেরিয়েবলগুলো সেট করুন।',
    'admin.confirm': 'নিশ্চিত করুন',
    'admin.no': 'না',
    'admin.yes_delete': 'হ্যাঁ, মুছুন',
    'admin.new_news': 'নতুন সংবাদ',
    'admin.total_news': 'মোট সংবাদ',
    'admin.total_views': 'মোট ভিউ',
    'admin.trending_news': 'ট্রেন্ডিং সংবাদ',
    'admin.recent_news': 'সাম্প্রতিক সংবাদ',
    'admin.view_all': 'সব দেখুন',
    'admin.table_title': 'শিরোনাম',
    'admin.table_category': 'ক্যাটাগরি',
    'admin.table_date': 'প্রকাশকাল',
    'admin.table_action': 'অ্যাকশন',
    'admin.no_news_found': 'কোনো সংবাদ পাওয়া যায়নি।',
    'admin.edit': 'এডিট',
    'admin.deleting': 'মুছছে...',
    'admin.delete': 'ডিলিট',
    'admin.scrolling_title': 'স্ক্রলিং শিরোনাম',
    'admin.new_title_placeholder': 'নতুন শিরোনাম লিখুন...',
    'admin.turn_off': 'বন্ধ করুন',
    'admin.turn_on': 'চালু করুন',
    'admin.no_title': 'কোনো শিরোনাম নেই।',
    'admin.ad_management': 'বিজ্ঞাপন ব্যবস্থাপনা (হেডলাইনের নিচে)',
    'admin.ad_image_placeholder': 'ছবির URL (যেমন: https://example.com/ad.jpg)',
    'admin.ad_link_placeholder': 'লিংক URL (ক্লিক করলে যেখানে যাবে)',
    'admin.add': 'যোগ করুন',
    'admin.no_ad': 'কোনো বিজ্ঞাপন নেই।',
    'admin.social_links': 'সোশ্যাল মিডিয়া লিংক',
    'admin.saving': 'সংরক্ষণ হচ্ছে...',
    'admin.save': 'সংরক্ষণ করুন',
    'admin.ramadan_schedule': 'রমজানের সময়সূচী ও আজান এলার্ট',
    'admin.sehri_end': 'সেহরির শেষ সময়',
    'admin.sehri_placeholder': 'যেমন: 04:45 AM',
    'admin.iftar_time': 'ইফতারের সময়',
    'admin.iftar_placeholder': 'যেমন: 06:15 PM',
    'admin.enable_timer': 'টাইমার ও এলার্ট চালু করুন',
    'admin.audio_error': 'অডিও প্লে করতে সমস্যা হয়েছে। ব্রাউজারে একবার ক্লিক করে আবার চেষ্টা করুন।',
    'admin.stop_azan': 'আজান বন্ধ করুন',
    'admin.test_azan': 'আজান টেস্ট করুন',
    'admin.update_schedule': 'সময়সূচী আপডেট করুন',
    'admin.page_content': 'পেজ কন্টেন্ট ব্যবস্থাপনা (About, Privacy, etc.)',
    'admin.page_content_management': 'পেজ কন্টেন্ট ব্যবস্থাপনা (About, Privacy, etc.)',
    'admin.about_us': 'আমাদের সম্পর্কে (About Us)',
    'admin.html_placeholder': 'HTML কন্টেন্ট এখানে দিন...',
    'admin.privacy_policy': 'গোপনীয়তা নীতি (Privacy Policy)',
    'admin.terms_conditions': 'ব্যবহারের শর্তাবলী (Terms & Conditions)',
    'admin.contact_us': 'যোগাযোগ (Contact Us)',
    'admin.copyright_text': 'কপিরাইট টেক্সট (Copyright Text)',
    'admin.copyright_placeholder': '© 2026 দৈনিক বরগুনা। সর্বস্বত্ব সংরক্ষিত।',
    'admin.save_page_settings': 'পেজ সেটিংস সংরক্ষণ করুন',
    'admin.login_title': 'অ্যাডমিন লগইন',
    'admin.login_failed': 'লগইন ব্যর্থ হয়েছে। ইমেইল বা পাসওয়ার্ড সঠিক নয়।',
    'admin.back_to_home': 'প্রচ্ছদে ফিরে যান',
    'admin.email_address': 'ইমেইল ঠিকানা',
    'admin.password': 'পাসওয়ার্ড',
    'admin.logging_in': 'লগইন হচ্ছে...',
    'admin.login': 'লগইন করুন',
    'admin.all_news': 'সকল সংবাদ',
    'admin.panel': 'অ্যাডমিন প্যানেল',
    'admin.change_theme': 'থিম পরিবর্তন',
    'admin.logout': 'লগআউট',
    'admin.add_news': 'সংবাদ যোগ করুন',
    'admin.edit_news': 'সংবাদ এডিট করুন',
    'admin.settings': 'সেটিংস',
    'admin.cancel': 'বাতিল',
  },
  en: {
    'nav.home': 'Home',
    'nav.more': 'More',
    'nav.search': 'Search...',
    'nav.search_placeholder': 'Search news...',
    'nav.unions': 'Union News',
    'nav.download': 'Download (Windows)',
    'footer.about': 'About Us',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms & Conditions',
    'footer.contact': 'Contact',
    'footer.editor': 'Editor & Publisher',
    'footer.upazila': 'Upazilas',
    'footer.description': 'Your reliable source for the latest news, politics, economy, entertainment, sports, and lifestyle from Barguna district. We are always steadfast in our search for the truth.',
    'about.title': 'About Us',
    'about.subtitle': 'Dainik Barguna: Constant in search of truth',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in touch with us',
    'privacy.title': 'Privacy Policy',
    'terms.title': 'Terms & Conditions',
    'editor.title': 'Editor Info',
    'editor.contact_desc': 'Use the following methods to contact Md. Zunayed Al Hasan, Editor and Publisher of Dainik Barguna.',
    'nav.back': 'Go Back',
    'notfound.title': '404 - Page Not Found',
    'notfound.code': '404',
    'notfound.heading': 'Sorry, this page was not found!',
    'notfound.desc': 'The news or page you are looking for may have been removed or its address has changed. Please verify the address again.',
    'notfound.home': 'Back to Home',
    'notfound.back': 'Go Back',
    'category.all_barguna': 'All Barguna',
    'category.barguna_sadar': 'Barguna Sadar',
    'category.amtali': 'Amtali',
    'category.patharghata': 'Patharghata',
    'category.betagi': 'Betagi',
    'category.bamna': 'Bamna',
    'category.taltali': 'Taltali',
    'category.saradesh': 'National',
    'category.bishwo': 'World',
    'union.badarkhali': 'Badarkhali',
    'union.gourichanna': 'Gourichanna',
    'union.fuljhuri': 'Fuljhuri',
    'union.keorabunia': 'Keorabunia',
    'union.aylapatakata': 'Aylapatakata',
    'union.burirchar': 'Burirchar',
    'union.dholua': 'Dholua',
    'union.barguna_sadar': 'Barguna Sadar',
    'union.m_baliatali': 'M Baliatali',
    'union.naltona': 'Naltona',
    'union.gulisakhali': 'Gulisakhali',
    'union.kukua': 'Kukua',
    'union.athargachia': 'Athargachia',
    'union.haldiya': 'Haldiya',
    'union.chaora': 'Chaora',
    'union.amtali_sadar': 'Amtali Sadar',
    'union.arpangashia': 'Arpangashia',
    'union.panchakoralia': 'Panchakoralia',
    'union.chotobogi': 'Chotobogi',
    'union.koraibaria': 'Koraibaria',
    'union.sharikkhali': 'Sharikkhali',
    'union.borobogi_sadar': 'Borobogi Sadar',
    'union.nishanbaria': 'Nishanbaria',
    'union.sonakata': 'Sonakata',
    'union.bibichini': 'Bibichini',
    'union.betagi_sadar': 'Betagi Sadar',
    'union.hosnabad': 'Hosnabad',
    'union.mokamia': 'Mokamia',
    'union.buramajumdar': 'Buramajumdar',
    'union.kajirabad': 'Kajirabad',
    'union.sorishamuri': 'Sorishamuri',
    'union.bukabunia': 'Bukabunia',
    'union.bamna_sadar': 'Bamna Sadar',
    'union.ramna': 'Ramna',
    'union.douatala': 'Douatala',
    'union.raihanpur': 'Raihanpur Union',
    'union.nachnapara': 'Nachnapara Union',
    'union.charduani': 'Charduani Union',
    'union.patharghata_sadar': 'Patharghata Sadar Union',
    'union.kalmegha': 'Kalmegha Union',
    'union.kakchira': 'Kakchira Union',
    'union.kathaltali': 'Kathaltali Union',
    'district.barguna': 'Barguna',
    'district.amtali': 'Amtali',
    'district.patharghata': 'Patharghata',
    'district.betagi': 'Betagi',
    'district.bamna': 'Bamna',
    'district.taltali': 'Taltali',
    'site.title': 'Daily Barguna',
    'news.latest_desc': 'latest news - Daily Barguna',
    'news.headlines': 'Headlines',
    'news.live_now': 'Live Now 🔴',
    'news.live_desc': 'The session of the National Parliament is being broadcast live',
    'news.watch_live': 'Watch Live',
    'news.area': 'Area',
    'news.all_areas': 'All Areas',
    'news.attached_file': 'Attached File',
    'news.file_attached_desc': 'A file is attached to this news',
    'news.view_file': 'View File',
    'news.more_images': 'More Images',
    'news.topic': 'Topic',
    'news.related': 'Related News',
    'news.views': 'views',
    'news.share': 'Share',
    'news.search_results': 'Search Results',
    'news.search_news': 'Search News',
    'news.filter': 'Filter',
    'news.all_categories': 'All Categories',
    'news.all_authors': 'All Authors',
    'news.start_date': 'Start Date',
    'news.end_date': 'End Date',
    'news.clear_filters': 'Clear Filters',
    'news.no_results': 'No results found',
    'news.area_latest': 'Latest news from the area',
    'news.no_news_area': 'No news in this area',
    'news.no_news_area_desc': 'No news currently found in {union} area.',
    'news.search_union': 'Search union...',
    'news.all_unions': 'View all unions',
    'news.no_union': 'No union found',
    'footer.editor_name': 'Md. Zunayed Al Hasan',
    'footer.address': 'Sadar Road, Barguna - 8700, Bangladesh',
    'footer.email': 'Email',
    'footer.copyright': '© {year} Daily Barguna. All rights reserved.',
    'common.read_more': 'Read More',
    'common.show_less': 'Show Less',
    'common.latest': 'Latest News',
    'common.popular': 'Popular',
    'common.share': 'Share',
    'common.date_en': 'English Date',
    'common.date_bn': 'Bangla Date',
    'common.date_hijri': 'Hijri Date',
    'ramadan.iftar': 'Iftar Time',
    'ramadan.sehri': 'Sehri Time',
    'ramadan.sehri_end': 'Sehri Ends',
    'ramadan.iftar_time': 'Iftar Time',
    'ramadan.timer': 'Ramadan Timer',
    'ramadan.enable_alert': 'Enable Alert',
    'ramadan.stop_azan': 'Stop Azan',
    'news.district': 'District',
    'news.area_news': 'Area News',
    'news.published': 'Published',
    'news.file': 'Attached File',
    'news.video': 'Video',
    'news.images': 'More Images',
    'news.no_news': 'No news found',
    'news.no_news_category': 'No news found in this category.',
    'news.count': 'news',
    'search.results': 'Search Results',
    'search.no_results': 'Sorry, no results found for your search.',
    'download.title': 'App Download',
    'download.desc': 'Download Daily Barguna App',
    'download.heading': 'Daily Barguna App Download',
    'download.subheading': 'Download our official app and get all the news at your fingertips in the fastest time. Below are the instructions to download the app:',
    'download.instructions_title': 'Download and Install Instructions:',
    'download.step1': '<strong>First click on Download Now:</strong> Then click on "Download anyway" to download the app.',
    'download.step2': '<strong>Click on INSTALL:</strong> Open the downloaded file and click the INSTALL button.',
    'download.step3': '<strong>Click on More Details:</strong> If the "Play Protect hasn\'t seen this app" message appears, click on "More details".',
    'download.step4': '<strong>Click on Install Without Scanning:</strong> Then click on the "Install without scanning" button.',
    'download.step5': '<strong>Security Verification:</strong> Give permission with your phone\'s Fingerprint or Pin, then complete the app installation.',
    'download.button': 'Download Now',
    'admin.add_new_news': 'Add New News',
    'admin.title': 'Title',
    'admin.title_placeholder': 'Enter news title',
    'admin.short_description': 'Short Description',
    'admin.short_description_placeholder': 'Enter short description',
    'admin.main_news': 'Main News',
    'admin.main_news_placeholder': 'Enter main news here...',
    'admin.media': 'Media',
    'admin.image_url': 'Image URL',
    'admin.additional_images': 'Additional Images',
    'admin.image_link_placeholder': 'Image Link (https://...)',
    'admin.image_caption_placeholder': 'Image Caption (Optional)',
    'admin.video_url': 'Video URL',
    'admin.video_url_placeholder': 'YouTube or other video link',
    'admin.metadata': 'Metadata',
    'admin.file_link': 'File Link',
    'admin.file_link_placeholder': 'PDF or other file link',
    'admin.category': 'Category',
    'admin.district': 'District',
    'admin.select_district': 'Select District',
    'admin.union_area': 'Union/Area',
    'admin.search_union_placeholder': 'Search Union...',
    'admin.reporter': 'Reporter',
    'admin.keywords': 'Keywords (SEO)',
    'admin.keywords_placeholder': 'Separate with comma (e.g., Barguna, News, Politics)',
    'admin.mark_as_trending': 'Mark as Trending',
    'admin.trending_description': 'This news will show in the trending section on homepage',
    'admin.preview': 'Preview',
    'admin.ramadan_timer': 'Ramadan Timer',
    'admin.sehri_time': 'Sehri Time',
    'admin.timer_alert_on': 'Timer Alert On',
    'admin.dashboard': 'Dashboard',
    'admin.confirm_delete': 'Are you sure you want to delete this news?',
    'admin.delete_success': 'News deleted successfully.',
    'admin.delete_error': 'Error deleting news.',
    'admin.confirm_title_delete': 'Are you sure you want to delete this title?',
    'admin.title_delete_success': 'Title deleted successfully.',
    'admin.title_delete_error': 'Error deleting title.',
    'admin.confirm_ad_delete': 'Are you sure you want to delete this ad?',
    'admin.ad_delete_success': 'Ad deleted successfully.',
    'admin.ad_delete_error': 'Error deleting ad.',
    'admin.social_update_success': 'Social media links updated successfully.',
    'admin.social_update_error': 'Error updating social links.',
    'admin.ramadan_update_success': 'Ramadan schedule updated successfully.',
    'admin.ramadan_update_error': 'Error updating schedule.',
    'admin.page_update_success': 'Page settings updated successfully.',
    'admin.page_update_error': 'Error updating page settings.',
    'admin.title_update_success': 'Title updated successfully.',
    'admin.title_update_error': 'Error updating title.',
    'admin.ad_update_success': 'Ad updated successfully.',
    'admin.ad_update_error': 'Error updating ad.',
    'admin.title_status_on': 'Title enabled.',
    'admin.title_status_off': 'Title disabled.',
    'admin.ad_status_on': 'Ad enabled.',
    'admin.ad_status_off': 'Ad disabled.',
    'admin.passcode_locked': 'Wrong passcode 3 times! Please wait 1 minute.',
    'admin.passcode_wrong': 'Wrong passcode! You have {attempts} attempts left.',
    'admin.passcode_verify': 'Verify Passcode',
    'admin.enter_passcode': 'Enter Passcode',
    'admin.wait_seconds': 'Wait {seconds} seconds',
    'admin.passcode': 'Passcode',
    'admin.verify': 'Verify',
    'error.title': 'Sorry, an error occurred',
    'error.message': 'There was a problem loading the application. Please refresh the page or try again later.',
    'error.refresh': 'Refresh Page',
    'admin.employee': 'Employee',
    'admin.firebase_not_connected': 'Firebase is not connected!',
    'admin.firebase_not_connected_desc': 'Firebase API Keys are not set in your Vercel or hosting environment. As a result, the real-time database will not work. Please go to Vercel Settings and set the ',
    'admin.firebase_not_connected_desc2': ' variables.',
    'admin.confirm': 'Confirm',
    'admin.no': 'No',
    'admin.yes_delete': 'Yes, Delete',
    'admin.new_news': 'New News',
    'admin.total_news': 'Total News',
    'admin.total_views': 'Total Views',
    'admin.trending_news': 'Trending News',
    'admin.recent_news': 'Recent News',
    'admin.view_all': 'View All',
    'admin.table_title': 'Title',
    'admin.table_category': 'Category',
    'admin.table_date': 'Published Date',
    'admin.table_action': 'Action',
    'admin.no_news_found': 'No news found.',
    'admin.edit': 'Edit',
    'admin.deleting': 'Deleting...',
    'admin.delete': 'Delete',
    'admin.scrolling_title': 'Scrolling Title',
    'admin.new_title_placeholder': 'Enter new title...',
    'admin.turn_off': 'Turn Off',
    'admin.turn_on': 'Turn On',
    'admin.no_title': 'No title found.',
    'admin.ad_management': 'Ad Management (Below Headline)',
    'admin.ad_image_placeholder': 'Image URL (e.g., https://example.com/ad.jpg)',
    'admin.ad_link_placeholder': 'Link URL (Where to go on click)',
    'admin.add': 'Add',
    'admin.no_ad': 'No ads found.',
    'admin.social_links': 'Social Media Links',
    'admin.saving': 'Saving...',
    'admin.save': 'Save',
    'admin.ramadan_schedule': 'Ramadan Schedule & Azan Alert',
    'admin.sehri_end': 'Sehri End Time',
    'admin.sehri_placeholder': 'e.g., 04:45 AM',
    'admin.iftar_time': 'Iftar Time',
    'admin.iftar_placeholder': 'e.g., 06:15 PM',
    'admin.enable_timer': 'Enable Timer & Alert',
    'admin.audio_error': 'Error playing audio. Click on the browser and try again.',
    'admin.stop_azan': 'Stop Azan',
    'admin.test_azan': 'Test Azan',
    'admin.update_schedule': 'Update Schedule',
    'admin.page_content': 'Page Content Management (About, Privacy, etc.)',
    'admin.page_content_management': 'Page Content Management (About, Privacy, etc.)',
    'admin.about_us': 'About Us',
    'admin.html_placeholder': 'Enter HTML content here...',
    'admin.privacy_policy': 'Privacy Policy',
    'admin.terms_conditions': 'Terms & Conditions',
    'admin.contact_us': 'Contact Us',
    'admin.copyright_text': 'Copyright Text',
    'admin.copyright_placeholder': '© 2026 Dainik Barguna. All rights reserved.',
    'admin.save_page_settings': 'Save Page Settings',
    'admin.login_title': 'Admin Login',
    'admin.login_failed': 'Login failed. Incorrect email or password.',
    'admin.back_to_home': 'Back to Home',
    'admin.email_address': 'Email Address',
    'admin.password': 'Password',
    'admin.logging_in': 'Logging in...',
    'admin.login': 'Login',
    'admin.all_news': 'All News',
    'admin.panel': 'Admin Panel',
    'admin.change_theme': 'Change Theme',
    'admin.logout': 'Logout',
    'admin.add_news': 'Add News',
    'admin.edit_news': 'Edit News',
    'admin.settings': 'Settings',
    'admin.cancel': 'Cancel',
  }
};
