import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'bn' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  getCategoryTranslation: (category: string) => string;
  getUnionTranslation: (union: string) => string;
  getDistrictTranslation: (district: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'bn';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  // Simple translation helper
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const getCategoryTranslation = (category: string): string => {
    const categoryMap: { [key: string]: string } = {
      'সমগ্র বরগুনা': 'category.all_barguna',
      'বরগুনা সদর': 'category.barguna_sadar',
      'আমতলী': 'category.amtali',
      'পাথরঘাটা': 'category.patharghata',
      'বেতাগী': 'category.betagi',
      'বামনা': 'category.bamna',
      'তালতলী': 'category.taltali',
      'সারাদেশ': 'category.saradesh',
      'বিশ্ব': 'category.bishwo'
    };

    const key = categoryMap[category];
    return key ? t(key) : category;
  };

  const getUnionTranslation = (union: string): string => {
    const unionMap: { [key: string]: string } = {
      'বদরখালী': 'union.badarkhali',
      'গৌরীচন্না': 'union.gourichanna',
      'ফুলঝুড়ি': 'union.fuljhuri',
      'কেওড়াবুনিয়া': 'union.keorabunia',
      'আয়লাপাতাকাটা': 'union.aylapatakata',
      'বুড়িরচর': 'union.burirchar',
      'ঢলুয়া': 'union.dholua',
      'বরগুনা সদর': 'union.barguna_sadar',
      'এম বালিয়াতলী': 'union.m_baliatali',
      'নলটোনা': 'union.naltona',
      'গুলিসাখালী': 'union.gulisakhali',
      'কুকুয়া': 'union.kukua',
      'আঠারগাছিয়া': 'union.athargachia',
      'হলদিয়া': 'union.haldiya',
      'চাওড়া': 'union.chaora',
      'আমতলী সদর': 'union.amtali_sadar',
      'আড়পাঙ্গাশিয়া': 'union.arpangashia',
      'পঁচাকোড়ালিয়া': 'union.panchakoralia',
      'ছোটবগী': 'union.chotobogi',
      'কড়ইবাড়ীয়া': 'union.koraibaria',
      'শারিকখালী': 'union.sharikkhali',
      'বড়বগী সদর': 'union.borobogi_sadar',
      'নিশানবাড়ীয়া': 'union.nishanbaria',
      'সোনাকাটা': 'union.sonakata',
      'বিবিচিনি': 'union.bibichini',
      'বেতাগী সদর': 'union.betagi_sadar',
      'হোসনাবাদ': 'union.hosnabad',
      'মোকামিয়া': 'union.mokamia',
      'বুড়ামজুমদার': 'union.buramajumdar',
      'কাজিরাবাদ': 'union.kajirabad',
      'সরিষামুড়ি': 'union.sorishamuri',
      'বুকাবুনিয়া': 'union.bukabunia',
      'বামনা সদর': 'union.bamna_sadar',
      'রামনা': 'union.ramna',
      'ডৌয়াতলা': 'union.douatala',
      'রায়হানপুর ইউনিয়ন': 'union.raihanpur',
      'নাচনাপাড়া ইউনিয়ন': 'union.nachnapara',
      'চরদুয়ানী ইউনিয়ন': 'union.charduani',
      'পাথরঘাটা সদর ইউনিয়ন': 'union.patharghata_sadar',
      'কালমেঘা ইউনিয়ন': 'union.kalmegha',
      'কাকচিড়া ইউনিয়ন': 'union.kakchira',
      'কাঠালতলী ইউনিয়ন': 'union.kathaltali'
    };

    const key = unionMap[union];
    return key ? t(key) : union;
  };

  const getDistrictTranslation = (district: string): string => {
    const districtMap: { [key: string]: string } = {
      'বরগুনা': 'district.barguna',
      'আমতলী': 'district.amtali',
      'পাথরঘাটা': 'district.patharghata',
      'বেতাগী': 'district.betagi',
      'বামনা': 'district.bamna',
      'তালতলী': 'district.taltali'
    };

    const key = districtMap[district];
    return key ? t(key) : district;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getCategoryTranslation, getUnionTranslation, getDistrictTranslation }}>
      <div className={language === 'en' ? 'font-inter' : 'font-sans'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations: Record<Language, Record<string, string>> = {
  bn: {
    'nav.home': 'প্রচ্ছদ',
    'nav.more': 'আরও',
    'nav.search': 'খুঁজুন...',
    'nav.search_placeholder': 'সংবাদ খুঁজুন...',
    'nav.unions': 'এলাকা ভিত্তিক সংবাদ',
    'nav.download': 'ডাউনলোড (Windows)',
    'footer.about': 'আমাদের সম্পর্কে',
    'footer.privacy': 'গোপনীয়তা নীতি',
    'footer.terms': 'শর্তাবলী',
    'footer.contact': 'যোগাযোগ',
    'footer.editor': 'সম্পাদক ও প্রকাশক',
    'footer.upazila': 'উপজেলা সমূহ',
    'footer.description': 'বরগুনা জেলার সর্বশেষ সংবাদ, রাজনীতি, অর্থনীতি, বিনোদন, খেলাধুলা এবং লাইফস্টাইলের নির্ভরযোগ্য উৎস। সত্যের সন্ধানে আমরা সর্বদা অবিচল।',
    'about.title': 'আমাদের সম্পর্কে',
    'about.subtitle': 'দৈনিক বরগুনা: সত্যের সন্ধানে অবিরাম',
    'contact.title': 'যোগাযোগ',
    'contact.subtitle': 'আমাদের সাথে যোগাযোগ করুন',
    'privacy.title': 'গোপনীয়তা নীতি',
    'terms.title': 'শর্তাবলী',
    'editor.title': 'সম্পাদক ও প্রকাশক',
    'editor.contact_desc': 'দৈনিক বরগুনা-এর সম্পাদক ও প্রকাশক মোঃ জুনায়েদ আল হাসান-এর সাথে যোগাযোগ করতে নিচের মাধ্যমগুলো ব্যবহার করুন।',
    'nav.back': 'পিছনে যান',
    'notfound.title': '৪০৪ - পাতা পাওয়া যায়নি',
    'notfound.code': '৪০৪',
    'notfound.heading': 'দুঃখিত, এই পাতাটি খুঁজে পাওয়া যায়নি!',
    'notfound.desc': 'আপনি যে সংবাদ বা পাতাটি খুঁজছেন তা হয়তো মুছে ফেলা হয়েছে অথবা এর ঠিকানা পরিবর্তন করা হয়েছে। সঠিক ঠিকানাটি পুনরায় যাচাই করুন।',
    'notfound.home': 'প্রচ্ছদে ফিরে যান',
    'notfound.back': 'পূর্ববর্তী পাতায় যান',
    'category.all_barguna': 'সমগ্র বরগুনা',
    'category.barguna_sadar': 'বরগুনা সদর',
    'category.amtali': 'আমতলী',
    'category.patharghata': 'পাথরঘাটা',
    'category.betagi': 'বেতাগী',
    'category.bamna': 'বামনা',
    'category.taltali': 'তালতলী',
    'category.saradesh': 'সারাদেশ',
    'category.bishwo': 'বিশ্ব',
    'union.badarkhali': 'বদরখালী',
    'union.gourichanna': 'গৌরীচন্না',
    'union.fuljhuri': 'ফুলঝুড়ি',
    'union.keorabunia': 'কেওড়াবুনিয়া',
    'union.aylapatakata': 'আয়লাপাতাকাটা',
    'union.burirchar': 'বুড়িরচর',
    'union.dholua': 'ঢলুয়া',
    'union.barguna_sadar': 'বরগুনা সদর',
    'union.m_baliatali': 'এম বালিয়াতলী',
    'union.naltona': 'নলটোনা',
    'union.gulisakhali': 'গুলিসাখালী',
    'union.kukua': 'কুকুয়া',
    'union.athargachia': 'আঠারগাছিয়া',
    'union.haldiya': 'হলদিয়া',
    'union.chaora': 'চাওড়া',
    'union.amtali_sadar': 'আমতলী সদর',
    'union.arpangashia': 'আড়পাঙ্গাশিয়া',
    'union.panchakoralia': 'পঁচাকোড়ালিয়া',
    'union.chotobogi': 'ছোটবগী',
    'union.koraibaria': 'কড়ইবাড়ীয়া',
    'union.sharikkhali': 'শারিকখালী',
    'union.borobogi_sadar': 'বড়বগী সদর',
    'union.nishanbaria': 'নিশানবাড়ীয়া',
    'union.sonakata': 'সোনাকাটা',
    'union.bibichini': 'বিবিচিনি',
    'union.betagi_sadar': 'বেতাগী সদর',
    'union.hosnabad': 'হোসনাবাদ',
    'union.mokamia': 'মোকামিয়া',
    'union.buramajumdar': 'বুড়ামজুমদার',
    'union.kajirabad': 'কাজিরাবাদ',
    'union.sorishamuri': 'সরিষামুড়ি',
    'union.bukabunia': 'বুকাবুনিয়া',
    'union.bamna_sadar': 'বামনা সদর',
    'union.ramna': 'রামনা',
    'union.douatala': 'ডৌয়াতলা',
    'union.raihanpur': 'রায়হানপুর ইউনিয়ন',
    'union.nachnapara': 'নাচনাপাড়া ইউনিয়ন',
    'union.charduani': 'চরদুয়ানী ইউনিয়ন',
    'union.patharghata_sadar': 'পাথরঘাটা সদর ইউনিয়ন',
    'union.kalmegha': 'কালমেঘা ইউনিয়ন',
    'union.kakchira': 'কাকচিড়া ইউনিয়ন',
    'union.kathaltali': 'কাঠালতলী ইউনিয়ন',
    'district.barguna': 'বরগুনা',
    'district.amtali': 'আমতলী',
    'district.patharghata': 'পাথরঘাটা',
    'district.betagi': 'বেতাগী',
    'district.bamna': 'বামনা',
    'district.taltali': 'তালতলী',
    'site.title': 'দৈনিক বরগুনা',
    'news.latest_desc': 'বিষয়ক সর্বশেষ সংবাদ - দৈনিক বরগুনা',
    'news.headlines': 'শিরোনাম',
    'news.live_now': 'সরাসরি সম্প্রচার 🔴',
    'news.live_desc': 'জাতীয় সংসদের অধিবেশন সরাসরি সম্প্রচারিত হচ্ছে',
    'news.watch_live': 'সরাসরি দেখুন',
    'news.area': 'এলাকা',
    'news.all_areas': 'সব এলাকা',
    'news.attached_file': 'সংযুক্ত ফাইল',
    'news.file_attached_desc': 'এই সংবাদের সাথে একটি ফাইল সংযুক্ত আছে',
    'news.view_file': 'ফাইল দেখুন',
    'news.more_images': 'আরও ছবি',
    'news.topic': 'বিষয়',
    'news.related': 'সম্পর্কিত সংবাদ',
    'news.views': 'বার দেখা হয়েছে',
    'news.share': 'শেয়ার করুন',
    'news.search_results': 'অনুসন্ধান ফলাফল',
    'news.search_news': 'সংবাদ অনুসন্ধান',
    'news.filter': 'ফিল্টার',
    'news.all_categories': 'সব বিভাগ',
    'news.all_authors': 'সব লেখক',
    'news.start_date': 'শুরুর তারিখ',
    'news.end_date': 'শেষের তারিখ',
    'news.clear_filters': 'ফিল্টার মুছুন',
    'news.no_results': 'কোন ফলাফল পাওয়া যায়নি',
    'news.area_latest': 'এলাকার সর্বশেষ সংবাদ',
    'news.no_news_area': 'এই এলাকায় কোন সংবাদ নেই',
    'news.no_news_area_desc': '{union} এলাকায় বর্তমানে কোন সংবাদ পাওয়া যায়নি।',
    'news.search_union': 'ইউনিয়ন খুঁজুন...',
    'news.all_unions': 'সব ইউনিয়ন দেখুন',
    'news.no_union': 'কোন ইউনিয়ন পাওয়া যায়নি',
    'footer.editor_name': 'মোঃ জুনায়েদ আল হাসান',
    'footer.address': 'সদর রোড, বরগুনা - ৮৭০০, বাংলাদেশ',
    'footer.email': 'ইমেইল',
    'footer.copyright': '© {year} দৈনিক বরগুনা। সর্বস্বত্ব সংরক্ষিত।',
    'common.read_more': 'আরও পড়ুন',
    'common.show_less': 'কম দেখুন',
    'common.latest': 'সর্বশেষ সংবাদ',
    'common.popular': 'জনপ্রিয়',
    'common.share': 'শেয়ার করুন',
    'common.date_en': 'ইংরেজি তারিখ',
    'common.date_bn': 'বাংলা তারিখ',
    'common.date_hijri': 'হিজরি তারিখ',
    'ramadan.iftar': 'ইফতারের সময়',
    'ramadan.sehri': 'সেহরির সময়',
    'ramadan.timer': 'রমজান টাইমার',
    'news.district': 'জেলা',
    'news.published': 'প্রকাশিত',
    'news.file': 'সংযুক্ত ফাইল',
    'news.video': 'ভিডিও',
    'news.images': 'আরও ছবি',
    'news.no_news': 'কোন সংবাদ পাওয়া যায়নি',
    'search.results': 'অনুসন্ধানের ফলাফল',
    'search.no_results': 'দুঃখিত, আপনার অনুসন্ধানের সাথে মেলে এমন কিছু পাওয়া যায়নি।',
    'admin.dashboard': 'ড্যাশবোর্ড',
    'admin.logout': 'লগআউট',
    'admin.add_news': 'সংবাদ যোগ করুন',
    'admin.edit_news': 'সংবাদ এডিট করুন',
    'admin.settings': 'সেটিংস',
    'admin.delete': 'ডিলিট',
    'admin.save': 'সংরক্ষণ করুন',
    'admin.cancel': 'বাতিল',
  },
  en: {
    'nav.home': 'Home',
    'nav.more': 'More',
    'nav.search': 'Search...',
    'nav.search_placeholder': 'Search news...',
    'nav.unions': 'Union News',
    'nav.download': 'Download (Windows)',
    'footer.about': 'About Us',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms & Conditions',
    'footer.contact': 'Contact',
    'footer.editor': 'Editor & Publisher',
    'footer.upazila': 'Upazilas',
    'footer.description': 'Your reliable source for the latest news, politics, economy, entertainment, sports, and lifestyle from Barguna district. We are always steadfast in our search for the truth.',
    'about.title': 'About Us',
    'about.subtitle': 'Dainik Barguna: Constant in search of truth',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in touch with us',
    'privacy.title': 'Privacy Policy',
    'terms.title': 'Terms & Conditions',
    'editor.title': 'Editor Info',
    'editor.contact_desc': 'Use the following methods to contact Md. Zunayed Al Hasan, Editor and Publisher of Dainik Barguna.',
    'nav.back': 'Go Back',
    'notfound.title': '404 - Page Not Found',
    'notfound.code': '404',
    'notfound.heading': 'Sorry, this page was not found!',
    'notfound.desc': 'The news or page you are looking for may have been removed or its address has changed. Please verify the address again.',
    'notfound.home': 'Back to Home',
    'notfound.back': 'Go Back',
    'category.all_barguna': 'All Barguna',
    'category.barguna_sadar': 'Barguna Sadar',
    'category.amtali': 'Amtali',
    'category.patharghata': 'Patharghata',
    'category.betagi': 'Betagi',
    'category.bamna': 'Bamna',
    'category.taltali': 'Taltali',
    'category.saradesh': 'National',
    'category.bishwo': 'World',
    'union.badarkhali': 'Badarkhali',
    'union.gourichanna': 'Gourichanna',
    'union.fuljhuri': 'Fuljhuri',
    'union.keorabunia': 'Keorabunia',
    'union.aylapatakata': 'Aylapatakata',
    'union.burirchar': 'Burirchar',
    'union.dholua': 'Dholua',
    'union.barguna_sadar': 'Barguna Sadar',
    'union.m_baliatali': 'M Baliatali',
    'union.naltona': 'Naltona',
    'union.gulisakhali': 'Gulisakhali',
    'union.kukua': 'Kukua',
    'union.athargachia': 'Athargachia',
    'union.haldiya': 'Haldiya',
    'union.chaora': 'Chaora',
    'union.amtali_sadar': 'Amtali Sadar',
    'union.arpangashia': 'Arpangashia',
    'union.panchakoralia': 'Panchakoralia',
    'union.chotobogi': 'Chotobogi',
    'union.koraibaria': 'Koraibaria',
    'union.sharikkhali': 'Sharikkhali',
    'union.borobogi_sadar': 'Borobogi Sadar',
    'union.nishanbaria': 'Nishanbaria',
    'union.sonakata': 'Sonakata',
    'union.bibichini': 'Bibichini',
    'union.betagi_sadar': 'Betagi Sadar',
    'union.hosnabad': 'Hosnabad',
    'union.mokamia': 'Mokamia',
    'union.buramajumdar': 'Buramajumdar',
    'union.kajirabad': 'Kajirabad',
    'union.sorishamuri': 'Sorishamuri',
    'union.bukabunia': 'Bukabunia',
    'union.bamna_sadar': 'Bamna Sadar',
    'union.ramna': 'Ramna',
    'union.douatala': 'Douatala',
    'union.raihanpur': 'Raihanpur Union',
    'union.nachnapara': 'Nachnapara Union',
    'union.charduani': 'Charduani Union',
    'union.patharghata_sadar': 'Patharghata Sadar Union',
    'union.kalmegha': 'Kalmegha Union',
    'union.kakchira': 'Kakchira Union',
    'union.kathaltali': 'Kathaltali Union',
    'district.barguna': 'Barguna',
    'district.amtali': 'Amtali',
    'district.patharghata': 'Patharghata',
    'district.betagi': 'Betagi',
    'district.bamna': 'Bamna',
    'district.taltali': 'Taltali',
    'site.title': 'Daily Barguna',
    'news.latest_desc': 'latest news - Daily Barguna',
    'news.headlines': 'Headlines',
    'news.live_now': 'Live Now 🔴',
    'news.live_desc': 'The session of the National Parliament is being broadcast live',
    'news.watch_live': 'Watch Live',
    'news.area': 'Area',
    'news.all_areas': 'All Areas',
    'news.attached_file': 'Attached File',
    'news.file_attached_desc': 'A file is attached to this news',
    'news.view_file': 'View File',
    'news.more_images': 'More Images',
    'news.topic': 'Topic',
    'news.related': 'Related News',
    'news.views': 'views',
    'news.share': 'Share',
    'news.search_results': 'Search Results',
    'news.search_news': 'Search News',
    'news.filter': 'Filter',
    'news.all_categories': 'All Categories',
    'news.all_authors': 'All Authors',
    'news.start_date': 'Start Date',
    'news.end_date': 'End Date',
    'news.clear_filters': 'Clear Filters',
    'news.no_results': 'No results found',
    'news.area_latest': 'Latest news from the area',
    'news.no_news_area': 'No news in this area',
    'news.no_news_area_desc': 'No news currently found in {union} area.',
    'news.search_union': 'Search union...',
    'news.all_unions': 'View all unions',
    'news.no_union': 'No union found',
    'footer.editor_name': 'Md. Zunayed Al Hasan',
    'footer.address': 'Sadar Road, Barguna - 8700, Bangladesh',
    'footer.email': 'Email',
    'footer.copyright': '© {year} Daily Barguna. All rights reserved.',
    'common.read_more': 'Read More',
    'common.show_less': 'Show Less',
    'common.latest': 'Latest News',
    'common.popular': 'Popular',
    'common.share': 'Share',
    'common.date_en': 'English Date',
    'common.date_bn': 'Bangla Date',
    'common.date_hijri': 'Hijri Date',
    'ramadan.iftar': 'Iftar Time',
    'ramadan.sehri': 'Sehri Time',
    'ramadan.timer': 'Ramadan Timer',
    'news.district': 'District',
    'news.published': 'Published',
    'news.file': 'Attached File',
    'news.video': 'Video',
    'news.images': 'More Images',
    'news.no_news': 'No news found',
    'search.results': 'Search Results',
    'search.no_results': 'Sorry, no results found for your search.',
    'admin.dashboard': 'Dashboard',
    'admin.logout': 'Logout',
    'admin.add_news': 'Add News',
    'admin.edit_news': 'Edit News',
    'admin.settings': 'Settings',
    'admin.delete': 'Delete',
    'admin.save': 'Save',
    'admin.cancel': 'Cancel',
  }
};
